server:
  port: 8456
spring:
  application:
    name: spring-mybatis

  redis:
    #redis 服务器地址
    host: localhost
    #端口号
    port: 6379
    #Redis数据库索引（默认为0）
    database: 0
    # Redis服务器连接密码（默认为空）
    password:

  datasource:
    url: jdbc:mysql://localhost:3306/spring?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    username: root
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8069/eureka
    register-with-eureka: true
    fetch-registry: true

feign:
  hystrix:
    enabled: true

  management:
    endpoints:
      web:
        exposure:
          include: hystrix.stream
